server:
  port: 9002
  error:
    include-message: always

spring:
  application:
    name: REVIEWS-COLLECTION
  datasource:
    url: jdbc:postgresql://localhost:5432/app60cat
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

keycloak:
  realm: dealership_reviews
  auth-server-url: http://localhost:8080/auth
  resource: REVIEWS-COLLECTION
  public-client: true
  bearer-only: true
