server:
  port: 9002
  error:
    include-message: always

spring:
  application:
    name: reviewcollection
  datasource:
    url: jdbc:postgresql://localhost:5432/app31cat
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true